site_name: Chicagoland Mesh
site_description: >-
  Join the local community of Meshtastic enthusiasts in the Chicagoland area, and collaborate in building a sustainable and interconnected network of decentralized nodes.
site_url: https://chicagolandmesh.org
#repo_url: https://github.com/chicagolandmesh/chicagolandmesh.org
copyright: 'Copyright &copy; 2024 Chicagoland Mesh <u><a href="https://github.com/chicagolandmesh/chicagolandmesh.org">Contributors</a></u><br><p style="margin:0">Chicagoland Mesh is not affilated with <u><a href="https://meshtastic.org" target="_blank" rel="noreferrer noopener">Meshtastic®</a></u>, nor endorsed by <u><a href="https://meshtastic.org/docs/legal/licensing-and-trademark" target="_blank" rel="noreferrer noopener">Meshtastic LLC</a></u>.</p>'
nav:
  - About: about/index.md
  - Guides:
    - guides/index.md
    - Getting Started:
      - guides/getting-started/index.md
      - Configuring Meshtastic: guides/getting-started/configure.md
      - Mistakes to Avoid: guides/getting-started/avoid-mistakes.md
    - Setup MQTT: guides/mqtt.md
    - Local Channel: guides/local-channel.md
    - Builds: 
      - guides/builds/index.md
  - News: news/index.md
  - Map: map/index.md
  - MeshView: https://meshview.chicagolandmesh.org
  #- Gallery: gallery/index.md
  - Resources: resources/index.md
  - Contact: contact/index.md

plugins:
  - tags:
      tags_file: tags.md
  - search
  - glightbox
  #- git-authors
  #- awesome-pages
  #- blog:
  #  - blog_dir: guides/builds
  #  - post_dir:

markdown_extensions:
  - md_in_html
  - attr_list
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

theme:
  name: 'material'
  custom_dir: 'overrides'
  logo: 'assets/images/logo-clear.svg'
  favicon: 'assets/images/logo-clear.svg'
  features:
      - navigation.tabs
      - navigation.path
      - navigation.section
      - navigation.path
      - navigation.indexes
      - navigation.top
      - navigation.footer
      - toc.integrate
      - search.suggest
      - search.share
      - announce.dismiss
  icon:
    repo: 'fontawesome/brands/github'
  palette:
    - media: "(prefers-color-scheme)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: chicago-light
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to auto

extra_css:
  - assets/stylesheets/extra.css

extra:
  generator: false
  social:
    - icon: custom/meshtastic
      link: https://meshtastic.org
      name: Check out the official Meshtastic site!
    - icon: 'fontawesome/brands/github'
      link: https://github.com/chicagolandmesh/chicagolandmesh.org
      name: Contribute to the github!
    - icon: fontawesome/brands/discord
      link: https://chicagolandmesh.org/discord
      name: Join the discord!
  #analytics: 
  #  provider:
  #  feedback:
  #    title: Was this page helpful?
  #    ratings:
  #      - icon: material/emoticon-happy-outline
  #        name: This page was helpful
  #        data: 1
  #        note: >-
  #          Thanks for your feedback!
  #      - icon: material/emoticon-sad-outline
  #        name: This page could be improved
  #        data: 0
  #        note: >- 
  #          Thanks for your feedback! Help us improve this page by
  #          using our <a href="..." target="_blank" rel="noopener">feedback form</a>.