authors:
  hamspiced:
    name: Hamspiced
    description: Contributor
    avatar: https://avatars.githubusercontent.com/u/41132615
    url: https://github.com/hamspiced
  dillon-conner:
    name: Dillon Conner
    description: Contributor
    avatar: https://avatars.githubusercontent.com/u/7284369
    url: https://github.com/dillon-conner
